sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-beta
before_install:
  - sudo apt-get update -qq
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
language: node_js
node_js:
  - "6"
  - "node"
